name: Create Release

on:
  push: 
    tags: [ "**" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Build Frontend
      run: |
        cd frontend
        bun install
        bun run build

    - name: Build Backend
      run: |
        cd backend
        go build -o gin-server ./

    - name: Prepare Release Directory
      run: |
        mkdir -p release/frontend
        mkdir -p release/backend
        cp -r frontend/dist/* release/frontend/
        cp backend/gin-server release/backend/

    - name: Create Release Archive
      run: |
        cd release
        zip -r ../gin-server.zip ./*
      

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: gin-server.zip  # Upload the artifacts from the release-artifacts directory
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
